### ISSUE TITLE
Integrate Restcomm SDKs

### ISSUE THREAD

**Issue by ctdao** [deklab/dektalk#5]
It is required to integrate and test Web SDK, iOS SDK and Android SDK.

Docs: http://documentation.telestax.com/connect/sdks/index.html

**Comment by drLeo** [comment]
An initialization of web client is now available for testing at
https://github.com/deklab/dektalk/tree/master/desktop

**Comment by ctdao** [comment]
Android app is available at:
https://github.com/deklab/dektalk/tree/master/mobile/android

iOS app is available at:
https://github.com/deklab/dektalk/tree/master/mobile/ios

I close this issue.
